language: ruby
rvm:
  - 2.2.0
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate test
  - bundle exec rake test
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:create db:migrate
addons:
  postgresql: "9.3"
test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres
notifications:
  slack: kevbac:neToW1cmiP0lQOc1WcBg75bL
bundler_args: --deployment --jobs=3 --retry=3
