default: &default
  adapter: postgresql
  encoding: unicode
  database: docker
  username: docker
  password: docker
  host: db
  pool: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
